import { riskCategories } from '@prism/domain';
import type { Decision, RiskScores } from '@prism/domain';
export function RiskBadge({ outcome }: { outcome: Decision['outcome'] }) { return <span className={`risk-badge ${outcome.toLowerCase()}`}><span className="status-dot" />{outcome === 'REVIEW' ? 'Review required' : outcome === 'BLOCK' ? 'Blocked' : 'Safe'}</span>; }
export function RiskBars({ scores }: { scores: RiskScores }) { return <div className="risk-bars">{riskCategories.map(category => <div className="risk-bar-row" key={category}><span>{category}</span><div className="risk-track"><div style={{ width: `${scores[category]}%`, background: scores[category] >= 75 ? 'var(--red)' : scores[category] >= 50 ? 'var(--amber)' : 'var(--accent)' }} /></div><strong className="mono">{scores[category]}</strong></div>)}</div>; }
export function RiskRadar({ scores }: { scores: RiskScores }) {
  const center = 150, radius = 100;
  const point = (index: number, value: number) => { const angle = index / 8 * Math.PI * 2 - Math.PI / 2; return `${center + Math.cos(angle) * radius * value},${center + Math.sin(angle) * radius * value}`; };
  return <svg viewBox="0 0 300 300" role="img" aria-label="Risk radar across eight dimensions" className="risk-radar">{[0.25, 0.5, 0.75, 1].map(level => <polygon key={level} points={riskCategories.map((_, i) => point(i, level)).join(' ')} fill="none" stroke="var(--border)" />)}{riskCategories.map((category, i) => <g key={category}><line x1={center} y1={center} x2={point(i, 1).split(',')[0]} y2={point(i, 1).split(',')[1]} stroke="var(--border)" /><text x={point(i, 1.23).split(',')[0]} y={point(i, 1.23).split(',')[1]} textAnchor="middle" dominantBaseline="middle" fill="var(--muted)" fontSize="10">{category}</text></g>)}<polygon points={riskCategories.map((category, i) => point(i, scores[category] / 100)).join(' ')} fill="var(--accent-soft)" stroke="var(--accent)" strokeWidth="2" />{riskCategories.map((category, i) => <circle key={category} cx={point(i, scores[category] / 100).split(',')[0]} cy={point(i, scores[category] / 100).split(',')[1]} r="3" fill="var(--accent)" />)}</svg>;
}
